---
- import_tasks: rootless.yml
- import_tasks: autoupdate.yml
- import_tasks: lingering.yml

- name: Create ~/.config/systemd/user/ directory
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.config/systemd/user"
    state: directory
    recurse: true

#
# Container Orchestration
# https://docs.ansible.com/ansible/latest/collections/containers/podman/podman_container_module.html
#
- name: Compose orchestration
  include_tasks: compose.yml
  vars:
    - remove_systemd_unit: "{{ (container.state == 'absent') | ternary(true, false) }}"
  loop: "{{ podman_containers }}"

# Make systemd aware of changes in units
- name: Run user daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user

# Start containers using systemd units
- name: Start containers
  include_tasks: start.yml
  vars:
    - container_name: "{{ item.name }}"
  when: container.started and container.state == 'created'
  loop: "{{ podman_containers }}"
